name: Semantic Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@v7.2.1
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}

  pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs/build/html

      - name: GitHub pages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install sphinx sphinx-autobuild
          export PATH=~/.local/bin:$PATH
          sphinx-build -M html "docs" "docs/build"
          cd docs/build/html
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "github pages"
          git push